"""modelselection table

Revision ID: 000176e80264
Revises: ab154462c198
Create Date: 2020-11-30 12:19:34.618221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000176e80264'
down_revision = 'ab154462c198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_modelselection_description'), 'modelselection', ['description'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelselection_description'), table_name='modelselection')
    # ### end Alembic commands ###
