"""variable table

Revision ID: 2118a258f90b
Revises: 9a8e6cf1e813
Create Date: 2020-12-01 13:59:41.347706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2118a258f90b'
down_revision = '9a8e6cf1e813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('number', sa.Integer(), nullable=True))
    op.drop_column('variable', 'regs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('regs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('variable', 'number')
    # ### end Alembic commands ###
