"""measurement table

Revision ID: 3524c0dfa29e
Revises: 9efda179f7e4
Create Date: 2020-11-24 14:10:00.630664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3524c0dfa29e'
down_revision = '9efda179f7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'new_time')
    op.drop_column('measurement', 'time_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('time_model', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('measurement', sa.Column('new_time', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
