"""Measurement table

Revision ID: 3570c47123be
Revises: e061eb523b8a
Create Date: 2020-11-23 14:46:46.166553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3570c47123be'
down_revision = 'e061eb523b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('new_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'new_time')
    # ### end Alembic commands ###
