"""modelselection table

Revision ID: 655f5e1f49b7
Revises: b769c922401c
Create Date: 2020-12-15 12:24:37.319370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655f5e1f49b7'
down_revision = 'b769c922401c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelselection', sa.Column('active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modelselection', 'active')
    # ### end Alembic commands ###
