"""modelselection table

Revision ID: 9a8e6cf1e813
Revises: 000176e80264
Create Date: 2020-11-30 12:27:39.663720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8e6cf1e813'
down_revision = '000176e80264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_modelselection_filename'), 'modelselection', ['filename'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelselection_filename'), table_name='modelselection')
    # ### end Alembic commands ###
