"""measurement table

Revision ID: 9efda179f7e4
Revises: e11db7352fd5
Create Date: 2020-11-24 13:35:36.199433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9efda179f7e4'
down_revision = 'e11db7352fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_measurement_time'), 'measurement', ['time'], unique=False)
    op.drop_column('measurement', 'time_current')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('time_current', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_measurement_time'), table_name='measurement')
    op.drop_column('measurement', 'time')
    # ### end Alembic commands ###
