"""variable table

Revision ID: ab154462c198
Revises: 3524c0dfa29e
Create Date: 2020-11-30 11:21:18.568097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab154462c198'
down_revision = '3524c0dfa29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_variable_type'), 'variable', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variable_type'), table_name='variable')
    op.drop_column('variable', 'type')
    # ### end Alembic commands ###
