"""measurement table

Revision ID: e11db7352fd5
Revises: ee97140cb6c1
Create Date: 2020-11-24 12:12:42.367986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e11db7352fd5'
down_revision = 'ee97140cb6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('time_current', sa.Time(), nullable=True))
    op.add_column('measurement', sa.Column('time_model', sa.Float(), nullable=True))
    op.drop_column('measurement', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('measurement', 'time_model')
    op.drop_column('measurement', 'time_current')
    # ### end Alembic commands ###
