"""Variable table

Revision ID: ee97140cb6c1
Revises: 3570c47123be
Create Date: 2020-11-23 16:54:50.871424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee97140cb6c1'
down_revision = '3570c47123be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_variable_name', table_name='variable')
    op.create_index(op.f('ix_variable_name'), 'variable', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variable_name'), table_name='variable')
    op.create_index('ix_variable_name', 'variable', ['name'], unique=True)
    # ### end Alembic commands ###
